module.exports = {
  extends: [
    '@oit/vue',
  ],
  globals: {
    uni: 'readonly',
    wx: 'readonly',
    getCurrentPages: 'readonly',
  },
  overrides: [
    {
      files: [
        'manifest.json',
      ],
      parser: 'jsonc-eslint-parser',
      rules: {
        'jsonc/key-spacing': 'off',
        'jsonc/indent': 'off',
      },
    },
  ],
  rules: {
    'vue/component-name-in-template-casing': [
      'error',
      'kebab-case',
    ],
    'vue/component-definition-name-casing': [
      'error',
      'kebab-case',
    ],
    'vue/order-in-components': ['warn', {
      order: [
        'el',
        'name',
        'key',
        'parent',
        'functional',
        ['components', 'directives', 'filters'],
        'extends',
        'mixins',
        ['provide', 'inject'],
        'inheritAttrs',
        'model',
        ['props', 'propsData'],
        'data',
        'computed',
        'watch',
        'ROUTER_GUARDS',
        // 'LIFECYCLE_HOOKS',

        'onLaunch',
        'onError',
        'onPageNotFound',
        'onThemeChange',

        'onInit',
        'onLoad',
        'onShow',
        'onReady',
        'onHide',
        'onUnload',
        'onUniNViewMessage',
        'onUnhandledRejection',
        'onResize',
        'onPullDownRefresh',
        'onReachBottom',
        'onTabItemTap',
        'onShareAppMessage',
        'onPageScroll',
        'onNavigationBarButtonTap',
        'onBackPress',
        'onNavigationBarSearchInputChanged',
        'onNavigationBarSearchInputConfirmed',
        'onNavigationBarSearchInputClicked',
        'onShareTimeline',
        'onAddToFavorites',

        'beforeCreate',
        'created',
        'beforeMount',
        'mounted',
        'beforeUpdate',
        'updated',
        'activated',
        'deactivated',
        'beforeDestroy',
        'destroyed',

        'methods',
        ['template', 'render'],
        'renderError',
      ],
    }],
  },
}
